-- GENERATED by gen_feature_view_sql.py from the feature registry. Do not edit
-- by hand — rerun the generator instead.
--
-- Pivots feature_store.feature_values_monthly into one row per customer per
-- month with one column per registered feature.
--
-- Grain is (global_customer_id, snapshot_month), not (customer_id, pnl, month).
-- The serving table stores each global customer twice, once under each PnL, and
-- fills the other unit's features with NULL. Verified against the source: no
-- (global_customer_id, month, feature) key has two non-null values, so folding
-- the pair together with MAX is lossless and gives something better than either
-- half — a single row holding both GSM and VinFast features side by side. That
-- is what makes cross-unit comparison possible without a self-join.
--
-- Only the newest snapshot is exposed. The serving table is content-addressed
-- and appends history under a new source_snapshot_hash rather than overwriting,
-- so an unfiltered pivot would silently mix snapshots once a second one lands.

CREATE SCHEMA IF NOT EXISTS analytics;

DROP VIEW IF EXISTS analytics.fact_customer_features;

CREATE VIEW analytics.fact_customer_features AS
WITH latest_snapshot AS (
    SELECT source_snapshot_hash
    FROM feature_store.feature_values_monthly
    WHERE registry_version = '1.0.0'
    ORDER BY loaded_at DESC
    LIMIT 1
)
SELECT
    v.global_customer_id,
    v.snapshot_month,
    MAX(NULLIF(v.feature_value, '')::INT)
        FILTER (WHERE v.feature_name = 'gsm_event_event_total_count_daily') AS gsm_event_event_total_count_daily,
    MAX(NULLIF(v.feature_value, '')::INT)
        FILTER (WHERE v.feature_name = 'gsm_event_event_total_count_l12m') AS gsm_event_event_total_count_l12m,
    MAX(NULLIF(v.feature_value, '')::INT)
        FILTER (WHERE v.feature_name = 'gsm_event_event_total_count_l1w') AS gsm_event_event_total_count_l1w,
    MAX(NULLIF(v.feature_value, '')::INT)
        FILTER (WHERE v.feature_name = 'gsm_event_event_total_count_l2w') AS gsm_event_event_total_count_l2w,
    MAX(NULLIF(v.feature_value, '')::INT)
        FILTER (WHERE v.feature_name = 'gsm_event_event_total_count_l3m') AS gsm_event_event_total_count_l3m,
    MAX(NULLIF(v.feature_value, '')::INT)
        FILTER (WHERE v.feature_name = 'gsm_event_event_total_count_l6m') AS gsm_event_event_total_count_l6m,
    MAX(NULLIF(v.feature_value, '')::INT)
        FILTER (WHERE v.feature_name = 'gsm_transaction_canceled_txn_count_daily') AS gsm_transaction_canceled_txn_count_daily,
    MAX(NULLIF(v.feature_value, '')::INT)
        FILTER (WHERE v.feature_name = 'gsm_transaction_canceled_txn_count_l12m') AS gsm_transaction_canceled_txn_count_l12m,
    MAX(NULLIF(v.feature_value, '')::INT)
        FILTER (WHERE v.feature_name = 'gsm_transaction_canceled_txn_count_l1m') AS gsm_transaction_canceled_txn_count_l1m,
    MAX(NULLIF(v.feature_value, '')::INT)
        FILTER (WHERE v.feature_name = 'gsm_transaction_canceled_txn_count_l1w') AS gsm_transaction_canceled_txn_count_l1w,
    MAX(NULLIF(v.feature_value, '')::INT)
        FILTER (WHERE v.feature_name = 'gsm_transaction_canceled_txn_count_l2w') AS gsm_transaction_canceled_txn_count_l2w,
    MAX(NULLIF(v.feature_value, '')::INT)
        FILTER (WHERE v.feature_name = 'gsm_transaction_canceled_txn_count_l3m') AS gsm_transaction_canceled_txn_count_l3m,
    MAX(NULLIF(v.feature_value, '')::INT)
        FILTER (WHERE v.feature_name = 'gsm_transaction_canceled_txn_count_l6m') AS gsm_transaction_canceled_txn_count_l6m,
    MAX(NULLIF(v.feature_value, '')::INT)
        FILTER (WHERE v.feature_name = 'gsm_transaction_completed_txn_count_daily') AS gsm_transaction_completed_txn_count_daily,
    MAX(NULLIF(v.feature_value, '')::INT)
        FILTER (WHERE v.feature_name = 'gsm_transaction_completed_txn_count_l12m') AS gsm_transaction_completed_txn_count_l12m,
    MAX(NULLIF(v.feature_value, '')::INT)
        FILTER (WHERE v.feature_name = 'gsm_transaction_completed_txn_count_l1m') AS gsm_transaction_completed_txn_count_l1m,
    MAX(NULLIF(v.feature_value, '')::INT)
        FILTER (WHERE v.feature_name = 'gsm_transaction_completed_txn_count_l1w') AS gsm_transaction_completed_txn_count_l1w,
    MAX(NULLIF(v.feature_value, '')::INT)
        FILTER (WHERE v.feature_name = 'gsm_transaction_completed_txn_count_l2w') AS gsm_transaction_completed_txn_count_l2w,
    MAX(NULLIF(v.feature_value, '')::INT)
        FILTER (WHERE v.feature_name = 'gsm_transaction_completed_txn_count_l3m') AS gsm_transaction_completed_txn_count_l3m,
    MAX(NULLIF(v.feature_value, '')::INT)
        FILTER (WHERE v.feature_name = 'gsm_transaction_completed_txn_count_l6m') AS gsm_transaction_completed_txn_count_l6m,
    MAX(NULLIF(v.feature_value, '')::INT)
        FILTER (WHERE v.feature_name = 'vinfast_transaction_txn_canceled_count_daily') AS vinfast_transaction_txn_canceled_count_daily,
    MAX(NULLIF(v.feature_value, '')::INT)
        FILTER (WHERE v.feature_name = 'vinfast_transaction_txn_canceled_count_l12m') AS vinfast_transaction_txn_canceled_count_l12m,
    MAX(NULLIF(v.feature_value, '')::INT)
        FILTER (WHERE v.feature_name = 'vinfast_transaction_txn_canceled_count_l1m') AS vinfast_transaction_txn_canceled_count_l1m,
    MAX(NULLIF(v.feature_value, '')::INT)
        FILTER (WHERE v.feature_name = 'vinfast_transaction_txn_canceled_count_l1w') AS vinfast_transaction_txn_canceled_count_l1w,
    MAX(NULLIF(v.feature_value, '')::INT)
        FILTER (WHERE v.feature_name = 'vinfast_transaction_txn_canceled_count_l2w') AS vinfast_transaction_txn_canceled_count_l2w,
    MAX(NULLIF(v.feature_value, '')::INT)
        FILTER (WHERE v.feature_name = 'vinfast_transaction_txn_canceled_count_l3m') AS vinfast_transaction_txn_canceled_count_l3m,
    MAX(NULLIF(v.feature_value, '')::INT)
        FILTER (WHERE v.feature_name = 'vinfast_transaction_txn_canceled_count_l6m') AS vinfast_transaction_txn_canceled_count_l6m,
    MAX(NULLIF(v.feature_value, '')::INT)
        FILTER (WHERE v.feature_name = 'vinfast_transaction_txn_completed_count_daily') AS vinfast_transaction_txn_completed_count_daily,
    MAX(NULLIF(v.feature_value, '')::INT)
        FILTER (WHERE v.feature_name = 'vinfast_transaction_txn_completed_count_l12m') AS vinfast_transaction_txn_completed_count_l12m,
    MAX(NULLIF(v.feature_value, '')::INT)
        FILTER (WHERE v.feature_name = 'vinfast_transaction_txn_completed_count_l1m') AS vinfast_transaction_txn_completed_count_l1m,
    MAX(NULLIF(v.feature_value, '')::INT)
        FILTER (WHERE v.feature_name = 'vinfast_transaction_txn_completed_count_l1w') AS vinfast_transaction_txn_completed_count_l1w,
    MAX(NULLIF(v.feature_value, '')::INT)
        FILTER (WHERE v.feature_name = 'vinfast_transaction_txn_completed_count_l2w') AS vinfast_transaction_txn_completed_count_l2w,
    MAX(NULLIF(v.feature_value, '')::INT)
        FILTER (WHERE v.feature_name = 'vinfast_transaction_txn_completed_count_l3m') AS vinfast_transaction_txn_completed_count_l3m,
    MAX(NULLIF(v.feature_value, '')::INT)
        FILTER (WHERE v.feature_name = 'vinfast_transaction_txn_completed_count_l6m') AS vinfast_transaction_txn_completed_count_l6m
FROM feature_store.feature_values_monthly v
JOIN latest_snapshot s ON s.source_snapshot_hash = v.source_snapshot_hash
WHERE v.registry_version = '1.0.0'
GROUP BY v.global_customer_id, v.snapshot_month;

COMMENT ON VIEW analytics.fact_customer_features IS
    'One row per customer per month with the 34 registered feature store features as columns (feature store, đặc trưng khách hàng). Covers 2025-01 to 2025-12 and 200 customers only — a curated subset, NOT the full customer base in dim_customer. Both GSM and VinFast features sit on the same row, so cross-unit comparison needs no join. Join to analytics.dim_customer on global_customer_id for customer attributes. Note: this source counts cancelled transactions, which analytics.fact_transactions does not contain — the two do not reconcile, see the column descriptions.';

COMMENT ON COLUMN analytics.fact_customer_features.global_customer_id IS
    'Cross-company customer identifier (mã khách hàng toàn hệ thống). Join key to analytics.dim_customer.';
COMMENT ON COLUMN analytics.fact_customer_features.snapshot_month IS
    'Snapshot month as YYYY-MM (tháng). Every feature on the row is measured as of the end of this month.';

COMMENT ON COLUMN analytics.fact_customer_features.gsm_event_event_total_count_daily IS
    'Number of GSM app events for this customer on the snapshot day (số sự kiện trên app của GSM trong ngày), as of the snapshot month. Registry feature gsm_event_event_total_count_daily.';
COMMENT ON COLUMN analytics.fact_customer_features.gsm_event_event_total_count_l12m IS
    'Number of GSM app events for this customer over the last 12 months (số sự kiện trên app của GSM trong 12 tháng gần nhất), as of the snapshot month. Registry feature gsm_event_event_total_count_l12m.';
COMMENT ON COLUMN analytics.fact_customer_features.gsm_event_event_total_count_l1w IS
    'Number of GSM app events for this customer over the last 7 days (số sự kiện trên app của GSM trong 7 ngày gần nhất), as of the snapshot month. Registry feature gsm_event_event_total_count_l1w.';
COMMENT ON COLUMN analytics.fact_customer_features.gsm_event_event_total_count_l2w IS
    'Number of GSM app events for this customer over the last 14 days (số sự kiện trên app của GSM trong 14 ngày gần nhất), as of the snapshot month. Registry feature gsm_event_event_total_count_l2w.';
COMMENT ON COLUMN analytics.fact_customer_features.gsm_event_event_total_count_l3m IS
    'Number of GSM app events for this customer over the last 3 months (số sự kiện trên app của GSM trong 3 tháng gần nhất), as of the snapshot month. Registry feature gsm_event_event_total_count_l3m.';
COMMENT ON COLUMN analytics.fact_customer_features.gsm_event_event_total_count_l6m IS
    'Number of GSM app events for this customer over the last 6 months (số sự kiện trên app của GSM trong 6 tháng gần nhất), as of the snapshot month. Registry feature gsm_event_event_total_count_l6m.';
COMMENT ON COLUMN analytics.fact_customer_features.gsm_transaction_canceled_txn_count_daily IS
    'Number of GSM cancelled transactions for this customer on the snapshot day (số giao dịch bị huỷ của GSM trong ngày), as of the snapshot month. Registry feature gsm_transaction_canceled_txn_count_daily.';
COMMENT ON COLUMN analytics.fact_customer_features.gsm_transaction_canceled_txn_count_l12m IS
    'Number of GSM cancelled transactions for this customer over the last 12 months (số giao dịch bị huỷ của GSM trong 12 tháng gần nhất), as of the snapshot month. Registry feature gsm_transaction_canceled_txn_count_l12m.';
COMMENT ON COLUMN analytics.fact_customer_features.gsm_transaction_canceled_txn_count_l1m IS
    'Number of GSM cancelled transactions for this customer over the last 1 month (số giao dịch bị huỷ của GSM trong 1 tháng gần nhất), as of the snapshot month. Registry feature gsm_transaction_canceled_txn_count_l1m.';
COMMENT ON COLUMN analytics.fact_customer_features.gsm_transaction_canceled_txn_count_l1w IS
    'Number of GSM cancelled transactions for this customer over the last 7 days (số giao dịch bị huỷ của GSM trong 7 ngày gần nhất), as of the snapshot month. Registry feature gsm_transaction_canceled_txn_count_l1w.';
COMMENT ON COLUMN analytics.fact_customer_features.gsm_transaction_canceled_txn_count_l2w IS
    'Number of GSM cancelled transactions for this customer over the last 14 days (số giao dịch bị huỷ của GSM trong 14 ngày gần nhất), as of the snapshot month. Registry feature gsm_transaction_canceled_txn_count_l2w.';
COMMENT ON COLUMN analytics.fact_customer_features.gsm_transaction_canceled_txn_count_l3m IS
    'Number of GSM cancelled transactions for this customer over the last 3 months (số giao dịch bị huỷ của GSM trong 3 tháng gần nhất), as of the snapshot month. Registry feature gsm_transaction_canceled_txn_count_l3m.';
COMMENT ON COLUMN analytics.fact_customer_features.gsm_transaction_canceled_txn_count_l6m IS
    'Number of GSM cancelled transactions for this customer over the last 6 months (số giao dịch bị huỷ của GSM trong 6 tháng gần nhất), as of the snapshot month. Registry feature gsm_transaction_canceled_txn_count_l6m.';
COMMENT ON COLUMN analytics.fact_customer_features.gsm_transaction_completed_txn_count_daily IS
    'Number of GSM completed transactions for this customer on the snapshot day (số giao dịch hoàn thành của GSM trong ngày), as of the snapshot month. Registry feature gsm_transaction_completed_txn_count_daily.';
COMMENT ON COLUMN analytics.fact_customer_features.gsm_transaction_completed_txn_count_l12m IS
    'Number of GSM completed transactions for this customer over the last 12 months (số giao dịch hoàn thành của GSM trong 12 tháng gần nhất), as of the snapshot month. Registry feature gsm_transaction_completed_txn_count_l12m.';
COMMENT ON COLUMN analytics.fact_customer_features.gsm_transaction_completed_txn_count_l1m IS
    'Number of GSM completed transactions for this customer over the last 1 month (số giao dịch hoàn thành của GSM trong 1 tháng gần nhất), as of the snapshot month. Registry feature gsm_transaction_completed_txn_count_l1m.';
COMMENT ON COLUMN analytics.fact_customer_features.gsm_transaction_completed_txn_count_l1w IS
    'Number of GSM completed transactions for this customer over the last 7 days (số giao dịch hoàn thành của GSM trong 7 ngày gần nhất), as of the snapshot month. Registry feature gsm_transaction_completed_txn_count_l1w.';
COMMENT ON COLUMN analytics.fact_customer_features.gsm_transaction_completed_txn_count_l2w IS
    'Number of GSM completed transactions for this customer over the last 14 days (số giao dịch hoàn thành của GSM trong 14 ngày gần nhất), as of the snapshot month. Registry feature gsm_transaction_completed_txn_count_l2w.';
COMMENT ON COLUMN analytics.fact_customer_features.gsm_transaction_completed_txn_count_l3m IS
    'Number of GSM completed transactions for this customer over the last 3 months (số giao dịch hoàn thành của GSM trong 3 tháng gần nhất), as of the snapshot month. Registry feature gsm_transaction_completed_txn_count_l3m.';
COMMENT ON COLUMN analytics.fact_customer_features.gsm_transaction_completed_txn_count_l6m IS
    'Number of GSM completed transactions for this customer over the last 6 months (số giao dịch hoàn thành của GSM trong 6 tháng gần nhất), as of the snapshot month. Registry feature gsm_transaction_completed_txn_count_l6m.';
COMMENT ON COLUMN analytics.fact_customer_features.vinfast_transaction_txn_canceled_count_daily IS
    'Number of VinFast cancelled transactions for this customer on the snapshot day (số giao dịch bị huỷ của VinFast trong ngày), as of the snapshot month. Registry feature vinfast_transaction_txn_canceled_count_daily.';
COMMENT ON COLUMN analytics.fact_customer_features.vinfast_transaction_txn_canceled_count_l12m IS
    'Number of VinFast cancelled transactions for this customer over the last 12 months (số giao dịch bị huỷ của VinFast trong 12 tháng gần nhất), as of the snapshot month. Registry feature vinfast_transaction_txn_canceled_count_l12m.';
COMMENT ON COLUMN analytics.fact_customer_features.vinfast_transaction_txn_canceled_count_l1m IS
    'Number of VinFast cancelled transactions for this customer over the last 1 month (số giao dịch bị huỷ của VinFast trong 1 tháng gần nhất), as of the snapshot month. Registry feature vinfast_transaction_txn_canceled_count_l1m.';
COMMENT ON COLUMN analytics.fact_customer_features.vinfast_transaction_txn_canceled_count_l1w IS
    'Number of VinFast cancelled transactions for this customer over the last 7 days (số giao dịch bị huỷ của VinFast trong 7 ngày gần nhất), as of the snapshot month. Registry feature vinfast_transaction_txn_canceled_count_l1w.';
COMMENT ON COLUMN analytics.fact_customer_features.vinfast_transaction_txn_canceled_count_l2w IS
    'Number of VinFast cancelled transactions for this customer over the last 14 days (số giao dịch bị huỷ của VinFast trong 14 ngày gần nhất), as of the snapshot month. Registry feature vinfast_transaction_txn_canceled_count_l2w.';
COMMENT ON COLUMN analytics.fact_customer_features.vinfast_transaction_txn_canceled_count_l3m IS
    'Number of VinFast cancelled transactions for this customer over the last 3 months (số giao dịch bị huỷ của VinFast trong 3 tháng gần nhất), as of the snapshot month. Registry feature vinfast_transaction_txn_canceled_count_l3m.';
COMMENT ON COLUMN analytics.fact_customer_features.vinfast_transaction_txn_canceled_count_l6m IS
    'Number of VinFast cancelled transactions for this customer over the last 6 months (số giao dịch bị huỷ của VinFast trong 6 tháng gần nhất), as of the snapshot month. Registry feature vinfast_transaction_txn_canceled_count_l6m.';
COMMENT ON COLUMN analytics.fact_customer_features.vinfast_transaction_txn_completed_count_daily IS
    'Number of VinFast completed transactions for this customer on the snapshot day (số giao dịch hoàn thành của VinFast trong ngày), as of the snapshot month. Registry feature vinfast_transaction_txn_completed_count_daily.';
COMMENT ON COLUMN analytics.fact_customer_features.vinfast_transaction_txn_completed_count_l12m IS
    'Number of VinFast completed transactions for this customer over the last 12 months (số giao dịch hoàn thành của VinFast trong 12 tháng gần nhất), as of the snapshot month. Registry feature vinfast_transaction_txn_completed_count_l12m.';
COMMENT ON COLUMN analytics.fact_customer_features.vinfast_transaction_txn_completed_count_l1m IS
    'Number of VinFast completed transactions for this customer over the last 1 month (số giao dịch hoàn thành của VinFast trong 1 tháng gần nhất), as of the snapshot month. Registry feature vinfast_transaction_txn_completed_count_l1m.';
COMMENT ON COLUMN analytics.fact_customer_features.vinfast_transaction_txn_completed_count_l1w IS
    'Number of VinFast completed transactions for this customer over the last 7 days (số giao dịch hoàn thành của VinFast trong 7 ngày gần nhất), as of the snapshot month. Registry feature vinfast_transaction_txn_completed_count_l1w.';
COMMENT ON COLUMN analytics.fact_customer_features.vinfast_transaction_txn_completed_count_l2w IS
    'Number of VinFast completed transactions for this customer over the last 14 days (số giao dịch hoàn thành của VinFast trong 14 ngày gần nhất), as of the snapshot month. Registry feature vinfast_transaction_txn_completed_count_l2w.';
COMMENT ON COLUMN analytics.fact_customer_features.vinfast_transaction_txn_completed_count_l3m IS
    'Number of VinFast completed transactions for this customer over the last 3 months (số giao dịch hoàn thành của VinFast trong 3 tháng gần nhất), as of the snapshot month. Registry feature vinfast_transaction_txn_completed_count_l3m.';
COMMENT ON COLUMN analytics.fact_customer_features.vinfast_transaction_txn_completed_count_l6m IS
    'Number of VinFast completed transactions for this customer over the last 6 months (số giao dịch hoàn thành của VinFast trong 6 tháng gần nhất), as of the snapshot month. Registry feature vinfast_transaction_txn_completed_count_l6m.';

REVOKE ALL ON ALL TABLES IN SCHEMA analytics FROM PUBLIC;
